"""The framed review-request comment (FR-07, §6.2, AD-7, AD-15).

FR-07 is unusually prescriptive about *what the comment says*, because the comment is the entire UX
of the review loop — there is no other interface. It must:

* tag the PM (a real @mention, so they are notified — a plain "@name" notifies nobody, AD-7);
* request the exact §6.2 structured feedback format;
* ask the PM to review as a *user*, not an engineer ("put yourself in the users' shoes");
* state that the **only** way to pass is for the PM to move the Review ticket to Done themselves —
  feedback after Done is not processed, and they must not ask the agent to change status (AD-15).

This is a pure ADF builder, not an agent — the wording is a product decision, so it lives in code and
is asserted by test, not generated by an LLM (which could quietly drop the Done-only rule).
"""

from __future__ import annotations

from app.config.constants import FEEDBACK_BLOCK_FIELDS
from app.domain import adf

#: The §6.2 structured feedback template, shown to the PM in a code block.
_FEEDBACK_TEMPLATE = "\n".join(f"{field}: <...>" for field in FEEDBACK_BLOCK_FIELDS)


def build_review_request(*, pm_account_id: str, draft_page_url: str) -> dict:
    """The FR-07 review-request comment body (ADF)."""
    return adf.doc(
        adf.paragraph(
            adf.mention(pm_account_id),
            adf.text(" a first draft of the UserDoc is ready for your review: "),
            adf.link("open the draft", draft_page_url)
            if draft_page_url
            else adf.text("(draft link unavailable)"),
            adf.text("."),
        ),
        adf.paragraph(
            adf.strong("Please review it as a user would"),
            adf.text(
                " — put yourself in the users' shoes, not the engineer's. Does it help someone "
                "actually use the product?"
            ),
        ),
        adf.paragraph(
            adf.text(
                "If you have feedback, please give it in this exact format, one block per point:"
            )
        ),
        adf.code_block(_FEEDBACK_TEMPLATE),
        adf.paragraph(
            adf.text(
                "You can include several such blocks in one comment. Plain-language feedback is "
                "fine too — I'll restate it in this format and check with you before changing "
                "anything."
            )
        ),
        adf.paragraph(
            adf.strong("To approve: "),
            adf.text(
                "transition this ticket to Done yourself. That is the only way to pass the draft. "
                "Feedback added after the ticket is Done is not processed, and please don't ask me "
                "to change the status for you — the Done transition has to be your own action."
            ),
        ),
    )


def build_change_summary(*, pm_account_id: str, summary: str, draft_page_url: str) -> dict:
    """The FR-11 re-request comment: what changed, plus the same Done-only framing."""
    change_lines = [line.strip(" -*") for line in summary.splitlines() if line.strip()]
    changes_block = (
        adf.bullet_list(*change_lines)
        if change_lines
        else adf.paragraph(adf.text("(see the updated draft)"))
    )
    return adf.doc(
        adf.paragraph(
            adf.mention(pm_account_id),
            adf.text(" I've revised the draft based on your feedback. What changed:"),
        ),
        changes_block,
        adf.paragraph(
            adf.text("Updated draft: "),
            adf.link("open the draft", draft_page_url)
            if draft_page_url
            else adf.text("(link unavailable)"),
        ),
        adf.paragraph(
            adf.text(
                "Please review again. To approve, transition this ticket to Done yourself "
                "(the only pass signal); or leave more feedback in the "
            ),
            adf.text(" / ".join(FEEDBACK_BLOCK_FIELDS)),
            adf.text(" format."),
        ),
    )
