"""Prepare the vault for the Quartz static-site build (S-B5).

Quartz (a Node/TypeScript SSG) turns an Obsidian-style Markdown folder into a browsable site with a
graph view, backlinks, and full-text search — exactly the "read-only projection at a URL" this epic
promises (AD-28, D-45: public, no auth). The heavy lifting is Quartz's; this module is the small,
**offline-testable** Python seam around it:

  * `set_quartz_base_url` patches the `baseUrl` in Quartz's **own** `quartz.config.ts` (from config,
    AD-4 — never a literal in code). We patch rather than generate the whole config: a hand-written
    config drifts from Quartz's version (and an incomplete `theme` ships an unstyled, script-less site),
    so we keep Quartz's version-correct defaults (theme, layout, plugins) and change only the URL.
  * `render_custom_css` styles the "Suggested (AI — unverified)" callout so an AI-inferred edge reads
    as clearly provisional in the rendered site (the visual half of AD-30's quarantine).
  * `stage_content` copies the vault's `notes/` into Quartz's `content/` **byte-for-byte**, so the
    `[[wikilinks]]` the linker wrote resolve unchanged and the build is reproducible.

The actual `npx quartz build` runs off-box (CI) or in the nightly job, never on the 1 GB Droplet
(AD-21) — see `scripts/build_agent_b_site.py` and `deploy/build_site.sh`. This module shells out to
nothing; it is pure string + file-copy work, which is what keeps it in the offline unit suite.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

_NOTES_SUBDIR = "notes"
_BASEURL_LINE = re.compile(r'baseUrl:\s*"[^"]*"')
_PAGETITLE_LINE = re.compile(r'pageTitle:\s*"[^"]*"')


def set_quartz_base_url(config_ts: str, base_url: str) -> str:
    """Return Quartz's `quartz.config.ts` with only its `baseUrl` replaced by our host (AD-4).

    Quartz wants the bare host (no scheme, no trailing slash), e.g. `agent.poetroastery.com`. Everything
    else in the file — theme, layout, plugins — is left as Quartz shipped it for this version.
    """
    host = base_url.split("://", 1)[-1].rstrip("/")
    return _BASEURL_LINE.sub(f'baseUrl: "{host}"', config_ts, count=1)


def set_quartz_page_title(config_ts: str, title: str) -> str:
    """Return Quartz's config with only its `pageTitle` (the top-left site name) replaced (AD-4)."""
    safe = title.replace("\\", "\\\\").replace('"', '\\"')
    return _PAGETITLE_LINE.sub(f'pageTitle: "{safe}"', config_ts, count=1)


def render_index_md(title: str = "Internal Knowledge Base") -> str:
    """The vault has no landing page, but Quartz builds the site root (`index.html`) only from a
    `content/index.md`. Without it the homepage 404s (per-note URLs still work). This is that page —
    a thin welcome; the explorer, search, and graph do the actual navigation."""
    safe = title.replace('"', "'")
    return (
        "---\n"
        f'title: "{safe}"\n'
        "---\n\n"
        f"# {title}\n\n"
        "Search (top), or use the explorer and graph to browse. Every note here is generated from "
        "Confluence — open a note and follow its source link to the original page.\n"
    )


def render_custom_css() -> str:
    """Styling shipped alongside the config so the AI-suggested callout reads as provisional."""
    return (
        "/* GENERATED by agent_b.pipeline.publish (S-B5). The linker renders AI-suggested links as a\n"
        "   `> [!tip] Suggested (AI — unverified)` Obsidian callout; make it visually distinct so an\n"
        "   unverified edge is never mistaken for a deterministic one (the visual half of AD-30). */\n"
        ".callout[data-callout='tip'] {\n"
        "  border-left: 3px dashed var(--secondary);\n"
        "  opacity: 0.85;\n"
        "}\n"
    )


def stage_content(vault_dir: str, content_dir: str) -> int:
    """Copy the vault's notes into Quartz's `content/` byte-for-byte; returns the note count.

    A fresh copy each build (the target is wiped first) keeps the site a faithful mirror of the vault:
    a note deleted from the vault (S-B4 tombstone) does not linger in the published site.
    """
    source = Path(vault_dir) / _NOTES_SUBDIR
    target = Path(content_dir)
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)
    count = 0
    for note in sorted(source.glob("*.md")) if source.exists() else []:
        shutil.copyfile(note, target / note.name)
        count += 1
    return count
