"""Prepare the vault for the Quartz static-site build (S-B5).

Quartz (a Node/TypeScript SSG) turns an Obsidian-style Markdown folder into a browsable site with a
graph view, backlinks, and full-text search — exactly the "read-only projection at a URL" this epic
promises (AD-28, D-45: public, no auth). The heavy lifting is Quartz's; this module is the small,
**offline-testable** Python seam around it:

  * `render_quartz_config` emits the `quartz.config.ts` with the site's `baseUrl` injected **from
    config** (AD-4 — the URL is never a literal in code) and the graph/backlinks/search components on.
  * `render_custom_css` styles the "Suggested (AI — unverified)" callout so an AI-inferred edge reads
    as clearly provisional in the rendered site (the visual half of AD-30's quarantine).
  * `stage_content` copies the vault's `notes/` into Quartz's `content/` **byte-for-byte**, so the
    `[[wikilinks]]` the linker wrote resolve unchanged and the build is reproducible.

The actual `npx quartz build` runs off-box (CI) or in the nightly job, never on the 1 GB Droplet
(AD-21) — see `scripts/build_agent_b_site.py` and `deploy/build_site.sh`. This module shells out to
nothing; it is pure string + file-copy work, which is what keeps it in the offline unit suite.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from agent_b.config import AgentBConfig

_NOTES_SUBDIR = "notes"


def render_quartz_config(config: AgentBConfig) -> str:
    """The `quartz.config.ts` for this KB — `baseUrl` from config, graph/backlinks/search enabled."""
    base_url = config.publish.base_url.rstrip("/")
    host = base_url.split("://", 1)[-1]  # Quartz wants the bare host in `baseUrl`
    return f"""// GENERATED by agent_b.pipeline.publish.render_quartz_config (S-B5) — do not hand-edit.
// The KB's Quartz site config. baseUrl comes from AgentBConfig.publish (AD-4: no URL literal in code).
import {{ QuartzConfig }} from "./quartz/cfg"
import * as Plugin from "./quartz/plugins"

const config: QuartzConfig = {{
  configuration: {{
    pageTitle: "Internal Knowledge Base",
    enableSPA: true,
    enablePopovers: true,
    baseUrl: "{host}",
    ignorePatterns: ["private", "templates", ".obsidian"],
    defaultDateType: "created",
    theme: {{ cdnCaching: true }},
  }},
  plugins: {{
    transformers: [
      Plugin.FrontMatter(),
      Plugin.ObsidianFlavoredMarkdown({{ parseTags: true }}),
      Plugin.CrawlLinks({{ markdownLinkResolution: "shortest" }}),
      Plugin.Description(),
    ],
    filters: [Plugin.RemoveDrafts()],
    emitters: [
      Plugin.ContentPage(),
      Plugin.FolderPage(),
      Plugin.TagPage(),
      Plugin.ContentIndex({{ enableSiteMap: true }}),
      // Graph view, backlinks, and search are on by default via the ContentPage layout; the site is
      // read-only and unauthenticated (D-45).
    ],
  }},
}}

export default config
"""


def render_index_md() -> str:
    """The vault has no landing page, but Quartz builds the site root (`index.html`) only from a
    `content/index.md`. Without it the homepage 404s (per-note URLs still work). This is that page —
    a thin welcome; the explorer, search, and graph do the actual navigation."""
    return (
        "---\n"
        'title: "Internal Knowledge Base"\n'
        "---\n\n"
        "# Internal Knowledge Base\n\n"
        "Search (top), or use the explorer and graph to browse. Every note here is generated from "
        "Confluence — open a note and follow its source link to the original page.\n"
    )


def render_custom_css() -> str:
    """Styling shipped alongside the config so the AI-suggested callout reads as provisional."""
    return (
        "/* GENERATED by agent_b.pipeline.publish (S-B5). The linker renders AI-suggested links as a\n"
        "   `> [!tip] Suggested (AI — unverified)` Obsidian callout; make it visually distinct so an\n"
        "   unverified edge is never mistaken for a deterministic one (the visual half of AD-30). */\n"
        ".callout[data-callout='tip'] {\n"
        "  border-left: 3px dashed var(--secondary);\n"
        "  opacity: 0.85;\n"
        "}\n"
    )


def stage_content(vault_dir: str, content_dir: str) -> int:
    """Copy the vault's notes into Quartz's `content/` byte-for-byte; returns the note count.

    A fresh copy each build (the target is wiped first) keeps the site a faithful mirror of the vault:
    a note deleted from the vault (S-B4 tombstone) does not linger in the published site.
    """
    source = Path(vault_dir) / _NOTES_SUBDIR
    target = Path(content_dir)
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)
    count = 0
    for note in sorted(source.glob("*.md")) if source.exists() else []:
        shutil.copyfile(note, target / note.name)
        count += 1
    return count
